#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - 9
  - 8
addons:
  chrome: stable

#运行的脚本命令
script:  
  - npm run proxy
  - CI=false npm run build
  - npm run gh

cache:
  yarn: true
  directories:
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 3c2b37a0db521ddd11745edffed4e4d73aabb3cc  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: docs
  

